### ISSUE TITLE
Possible ruby 2.2 regression

### ISSUE THREAD

**Issue by erickguan** [discourse/onebox#297]
The document says `request_get` never raise. However it's not true.

```

2015-05-05 12:31:08 - TypeError - exception object expected:
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:266:in `raise'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:266:in `rescue in ensure in inflater'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:263:in `ensure in inflater'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:263:in `inflater'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:279:in `read_body_0'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:226:in `body'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:163:in `reading_body'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1420:in `block in transport_request'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1285:in `request_get'
        /Users/fantasticfears/Dev/onebox/lib/onebox/helpers.rb:39:in `fetch_response'
        /Users/fantasticfears/Dev/onebox/lib/onebox/engine/youku_onebox.rb:27:in `placeholder_html'
        /Users/fantasticfears/Dev/onebox/lib/onebox/preview.rb:21:in `placeholder_html'
        /Users/fantasticfears/Dev/onebox/lib/onebox/web.rb:28:in `block in <class:Web>'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /Users/fantasticfears/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        /Users/fantasticfears/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
localhost - - [05/May/2015:12:31:07 CST] "GET /onebox?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XNjM3MzAxNzc2.html HTTP/1.1" 500 183154
```

**Comment by SamSaffron** [comment]
yeah we should fix this.
